### ISSUE TITLE
Profile subgroup missing

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#104]
**Describe the bug**
Previously, profile subgroup was available.

**To Reproduce**
1. Install CLI.
2. Run `mg profile -h`
3. Output: `mg: 'profile' is not in the 'mg' command group. See 'mg --help'.`

**Expected behavior**

```cli
Group
    mg profile

Commands:
    add-cloud    : Add a custom cloud.
    delete-cloud : Deletes a user defined cloud.
    set-cloud    : Set a cloud.
    set-version  : Set version of graph to use.
    show-clouds  : Show list of supported clouds.
    show-profile : Show profile information.
    update-cloud : Update a user defined cloud.

For more specific examples, use: mg find "mg profile"
```
 
[AB#9370](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9370)

**Comment by MIchaelMainer** [comment]
Once this bug is addressed, there are other ones that we need to check whether they are still valid:
https://github.com/microsoftgraph/msgraph-cli/blob/task/samples-powershell/samples/powershell/3-Profile.ps1

**Comment by jobala** [comment]
We renamed the profile subgroup to cloud to align with azure-cli.
