### ISSUE TITLE
Rename azure_ad_endpoint to identity_endpoint in profile.json to match branding

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#107]
**Describe the bug**
The profile.json contains an entry called azure_ad_endpoint. A more appropriate endpoint for where we obtain bearer tokens is identity_endpoint.

https://github.com/microsoftgraph/msgraph-cli/search?q=azure_ad_endpoint 
 
[AB#9373](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9373)

**Comment by jobala** [comment]
We used `azure_ad_endpoint` in an effort to align with Azure's verbiage. Closing this reopen if you have further concerns on the effect of this on the user experience.
