### ISSUE TITLE
What is the purpose of record.txt?

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#108]
**Describe the bug**
In `C:\Users\{user}\.mg\`, there is a record.txt the contains information such as the identity authority, clientId, tenantId, userId, and username. How is this used?
 
[AB#9374](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9374)

**Comment by jobala** [comment]
This is used by azure-identity to create an AuthRecord object which is used for log in session persistence across requests.
