### ISSUE TITLE
No concept of /me

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#111]
**Describe the bug**
/me is a fundamental concept in Microsoft Graph. We need to support singletons, and this is the most important one to support as it is an alias for /users/user.

This is especially important as the current app is a delegate permission only app.
 
[AB#9404](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9404)

**Comment by jobala** [comment]
Do you mean a cli command that maps to `/me` endpoint ? It would be nice to add as part of this issue how it works in Powershell.

**Comment by MIchaelMainer** [comment]
Yes. PowerShell doesn't support /me directly. 

Customers can however use Invoke-MgGraphRequest -Uri "/me" to get "me" and pass the Id to any Get-MgUser* command. We should consider an equivalent to Invoke-MgGraphRequest so that we can make arbitrary calls. I will close this issue and open a feature request for arbitrary request.
