### ISSUE TITLE
Missing query parameter support

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#112]
**Describe the bug**
$top, $search, $count, $skip, $format not supported. Perhaps there is a way to set arbitrary query parameters that I haven't found. If these are supported, then let's consider this a doc bug.

Note that filter is supported, there is special syntax for that. 
 
[AB#9405](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9405)

**Comment by jobala** [comment]
We'll have to investigate OData query parameters but users can achieve this using JMESPath query language. Tagging this as enhancement becuase it's not a bug.
