### ISSUE TITLE
Using mg login with scopes and client id (bug-bash)

### ISSUE THREAD

**Issue by izaktumz-zz** [microsoftgraph/msgraph-cli-archived#122]
**Describe the bug**
mg login bug using client id and scopes

**To Reproduce**
1. Successfully Installed the cli
2. Typed the mg login command with the following parameters
    mg login --scopes "User.Read.All" --client-id  my-app-clientid
3. Redirected to Login Page
4. Error Message: Trouble Signing in

**Expected behavior**
Successful Login through the cli

**Actual behavior**
Trouble Signing in

**Screenshots**

**Recommendations**
Examples of Signing in using cli with different parameters 
[AB#9560](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9560)

**Comment by jobala** [comment]
@isaactumut what error message did you get?

**Comment by izaktumz-zz** [comment]
I got the error 

Sorry, but we’re having trouble signing you in.
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 

NB:I did not specify the reply url when making the request.There is no mention of specifying the reply url in the cli

**Comment by jobala** [comment]
You need to configure the reply url when registering your app. 

Considering this as a documentation bug, we need to tell users how to configure their apps.
