### ISSUE TITLE
Using mg login with scopes , client id and tenant id (bug-bash) 

### ISSUE THREAD

**Issue by izaktumz-zz** [microsoftgraph/msgraph-cli-archived#123]
**Describe the bug**
mg login bug using client id , scopes and tenant id

**To Reproduce**
1. Successfully Installed the cli
2. Typed the mg login command with the following parameters
    mg login --scopes "User.Read.All" --client-id  my-app-clientid  --tenant-id   app-tenant-id
3. Redirected to Login Page
4. Error Message: Trouble Signing in

**Expected behavior**
Successful Login through the cli

**Actual behavior**
Trouble Signing in

**Screenshots**

**Recommendations**
Examples of Signing in using cli with different parameters
 
[AB#9561](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9561)

**Comment by izaktumz-zz** [comment]
..

**Comment by jobala** [comment]
Similar to #122
