### ISSUE TITLE
mg profile -h results in an error

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-cli-archived#124]
**Describe the bug**
`mg profile -h` results in `mg: 'profile' is not in the 'mg' command group` error. The same also happens with `mg profile -help`.

**To Reproduce**
1. Use `mg login --scopes "user.read.all"` to login.
2. A default message appears with instructions on how to get help for `profile` commands.
3. Use` mg profile -h` as described in the default message.
4. `mg: 'profile' is not in the 'mg' command group` error is raised.

**Expected behavior**
`mg profile -h` should show help on how to use `mg profile` command group.

**Screenshots**
![image](https://user-images.githubusercontent.com/7061532/119186881-65413900-ba2d-11eb-9340-cb001c753fcd.png)

 
[AB#9565](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9565)

**Comment by jobala** [comment]
`mg profile` was renamed to `mg cloud`
