### ISSUE TITLE
Multiple auth re-prompt when running commands

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-cli-archived#126]
**Describe the bug**
I am re-prompted to sign in multiple times when running commands that requires scopes that I haven't consented to. e.g. `mg mail user list-message --user-id "USER_ID"`

**To Reproduce**
1. Remove previously consent scopes for `msgraph-cli` service principal.
2. Run `mg login --scopes "user.read"` with `user.read` scope. This signs you in successfully.
3. Run `mg mail user list-message --user-id "USER_ID"`. N.B. I haven't consent to the required permission - `Mail.Read`.
4. You'll get multiple authentication prompts.

**Expected behavior**
Running a command that requires scopes that I haven't consented to should throw an error with a hint of a HTTP 403 message.

**Screenshots**
![Auth bug](https://github.com/peombwa/storage-files/raw/main/2021-05-21_18-02-24.gif)

**Additional context**
N/A
 
[AB#9568](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9568)

**Comment by jobala** [comment]
What version of the CLI  are you using? This is what I get.

<img width="1209" alt="Screen Shot 2021-05-23 at 10 58 50 AM" src="https://user-images.githubusercontent.com/12011447/119252599-e1668880-bbb5-11eb-8ca1-e893d1b28211.png">

**Comment by MIchaelMainer** [comment]
I can't repro this. I get the same output as Japheth.

**Comment by peombwa** [comment]
I can still repro it on my VM. I am using:
``` powershell
PS C:\Users\WasongaP> mg -v
0.1.2

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Msgraph\CLI\python.exe'
```

Also, the GIF in the original issue should now be visible.

**Comment by roinochieng** [comment]
We're still investigating this edge case and marking it as a discussion as we gather more information and attempt to reproduce the issue.
