### ISSUE TITLE
App Insights Implementation

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-cli-archived#175]
Adding app insights to the CLI implementation to capture more app usage insights: https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview 
[AB#10577](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10577)

**Comment by calebkiage** [comment]
@roinochieng, according to the library's [PyPI page](https://pypi.org/project/applicationinsights/) applicationinsights is no longer supported. The suggested alternative is to use the `opencensus-ext-azure` library instead
