### ISSUE TITLE
mg command is used by another program in macOS. We need a new command for msgraph-cli

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/msgraph-cli-archived#26]
In macOS the mg command is used by the [mg editor](https://en.wikipedia.org/wiki/Mg_(editor)). 
[AB#6279](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6279)

**Comment by MIchaelMainer** [comment]
Well, we know we want consistency across CLI supported platforms, and mg editor is probably not going away. It'd be bad form to alias mg to our CLI. We'll need a new cli entry point.

```cli
gr login # compact, 'gr' is a great sound
gra login 
grap login # rhymes with crap, close to grep. Nope.
graph login # clarity, has flow
mgc login 
m.g login # namespace acronym may be useful if we created a separate beta CLI
m_g login # too many syllables when said out loud, requires shift key combo
m-g login
```

@darrelmiller Would we ever have a beta CLI? Would it be a side by side experience or part of standard CLI package? If it was its own, it would have its own entry point like `m.g.b` or `gr-beta`.

**Comment by jobala** [comment]
@darrelmiller @MIchaelMainer  & @ddyett  what do you think of using `msgraph` as the entry point?

**Comment by MIchaelMainer** [comment]
A bit longer than I like but we are a verbose people. Definitely shouldn't have any naming collisions. I like it.

**Comment by ddyett** [comment]
msgraph is probably fine at least for now.  There's maybe other options like mgc for microsoft graph cli, or mgs for microsoft graph service but I'm not into those either.

**Comment by jobala** [comment]
Alright, I will switch the commands to msgraph.

**Comment by MIchaelMainer** [comment]
@roinochieng

**Comment by ddyett** [comment]
@roinochieng can you drive on what the final name here should be for mac.
