### ISSUE TITLE
Add documentation on running msgraph-cli from a docker container

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/msgraph-cli-archived#31]
msgraph-cli is installed inside a docker container but users/contributers won't know this until they look at the `Dockerfile`

**Comment by jobala** [comment]
@ddyett users won't be able to log in when using the docker container because it doesn't have a browser and we log in users interactively. What do you think of adding support for device code authentication flow instead of #21.

**Comment by ddyett** [comment]
i think we'll need #21 at some point.  Do we allow passing in an appid

**Comment by jobala** [comment]
No we don't. Tracking it with #38

Will #38 make #21  redundant? If it does, it will be better to let the user pass an appId instead of passing an access token because passing access tokens is less secure and we won't be able to use azure-identity for token management -- token storage and renewal.
