### ISSUE TITLE
Can't launch browser for authentication from WSL

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#42]
**Describe the bug**

**To Reproduce**
1. Go to WSL for Ubuntu 20.04 using 
2. `./graph login --scopes user.read`
3. See error `g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)`

**Expected behavior**
Should work when using the Ubuntu WSL terminal or Windows Terminal and WSL

 
[AB#6770](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6770)

**Comment by magnus-longva-bouvet** [comment]
Having the same issue when running inside Docker container.

**Comment by jobala** [comment]
Launching the browser window from wsl depends on the users configuration and it is not possible when the CLI is running in a docker container. Consider using device code flow.
