### ISSUE TITLE
Determine Linux distro support and testing

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#44]
**Is your feature request related to a problem? Please describe.**
Specify which Linux distros we test and support for this.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

 
[AB#6771](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6771)

**Comment by darrelmiller** [comment]
Is there any reason why we shouldn't just copy what AZ CLI does?
