### ISSUE TITLE
Update the installer assets to use Microsoft Graph branding

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#45]
**Describe the bug**
Installer still uses Azure branding

**To Reproduce**
Just install and find out. 

 
[AB#6772](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6772)

**Comment by MIchaelMainer** [comment]
@roinochieng We need to get updated branding assets in the installer. The current customer experience on install uses Azure assets. We need to make sure that we use approved assets that align with brand standard.

**Comment by roinochieng** [comment]
We made some progress with updating the main branding asset. We're pending the footer image and pending a response from the PMM team.
