### ISSUE TITLE
Use Official Client Id 

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/msgraph-cli-archived#59]
The CLI is using an unofficial client id from a Contoso tenant. We should use one from our tenant. 
[AB#7049](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7049)

**Comment by MIchaelMainer** [comment]
It needs to be published in the Microsoft tenant so that it can be classified as verified.

![image](https://user-images.githubusercontent.com/8527305/117732749-40cf9c00-b1a5-11eb-98f8-7aa39d459ed2.png)
