### ISSUE TITLE
As a user, I want to access a log that contains the client-request-id header set on my request 

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#61]
**Is your feature request related to a problem? Please describe.**
When users encounter an error, they will want to report it with as much information as possible. A default logging handler that captures information about their call will help them receive support. 

**Describe the solution you'd like**
Python Core should provide a default logging handler to capture information about features used and the calls being made, including information from the headers like `client-request-id`. A developer should also be able to provide a custom logging handler. 

**Describe alternatives you've considered**
Logging from the CLI itself should be avoided as this is common scenario to both the CLI and the Microsoft Graph Python client.
 
[AB#7657](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7657)

**Comment by jobala** [comment]
Closing this because the feature is already implemented
