### ISSUE TITLE
Long file name support in windows - registry setting

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#88]
**Describe the bug**
Windows does not support long file paths. We create very long file paths with the extensions. When installing the CLI, we will want to make sure this is supported with the following registry setting.

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
DWORD LongPathsEnabled = 1 

There is a way to support this via the installer - Git for Windows has this option in the installer.
 
[AB#8899](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8899)

**Comment by jobala** [comment]
Hi Michael,

I made  a build of the CLI with extensions that were failing to build in the CI/CD environment because of long filepaths and was able to install msgraph-cli with these extensions without having to edit the registry.

**Comment by MIchaelMainer** [comment]
Fixed and validated in https://github.com/microsoftgraph/msgraph-cli/pull/191
